apiVersion: apps/v1
kind: Deployment
metadata:
 name: nzngarage-longtail-suggestion-backend
spec:
 replicas: 1
 selector:
     matchLabels:
       app: nzngarage-longtail-suggestion-backend
 template:
   metadata:
     labels:
       app: nzngarage-longtail-suggestion-backend
   spec:     # pod spec                  
     containers:
     - name: nzngarage-longtail-suggestion-backend
       image: us.icr.io/nzngarage/nzngarage-longtail-suggestion-backend:latest
       ports:
         - containerPort: 6005
       env:
          - name: MONGO_DB_URL
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongoURL
          - name: MONGO_DB_NAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongoName
          - name: MONGO_DB_CERTIFICATE
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongoCA
          - name: SEMRUSH_APIKEY
            valueFrom:
              secretKeyRef:
                name: semrush-secret
                key: semrushApiKey
          - name: MSSQL_HOST
            valueFrom:
              secretKeyRef:
                name: mssql-secret
                key: mssqlHost
          - name: MSSQL_DB
            valueFrom:
              secretKeyRef:
                name: mssql-secret
                key: mssqlDb
          - name: MSSQL_USERNAME
            valueFrom:
              secretKeyRef:
                name: mssql-secret
                key: mssqlUsername
          - name: MSSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql-secret
                key: mssqlPassword
          - name: SEMRUSH_APIKEY
            valueFrom:
              secretKeyRef:
                name: semrush-secret
                key: semrushApiKey
       imagePullPolicy: Always