apiVersion: v1
kind: Service
metadata:
  labels:
    app: nzngarage-backend
  name: nzngarage-backend-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nzngarage-backend
  type: NodePort